# Generated by Django 2.1.3 on 2019-10-31 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='接口标识')),
                ('app', models.CharField(max_length=50, verbose_name='app名字')),
                ('model', models.CharField(max_length=50, verbose_name='数据模型名字')),
                ('operation', models.CharField(choices=[('list', '查看'), ('retrieve', '详情'), ('create', '新建'), ('update', '全部更新'), ('replace', '部分更新'), ('delete', '删除'), ('update_by_condition', '批量更新'), ('delete_by_condition', '批量删除'), ('func', '云函数')], max_length=20, verbose_name='操作')),
                ('ordering', models.CharField(blank=True, default='', max_length=500, verbose_name='排序')),
                ('expand_fields', models.CharField(blank=True, default='', max_length=500, verbose_name='展开字段')),
                ('func_name', models.CharField(blank=True, default='', max_length=50, verbose_name='云函数名称')),
                ('summary', models.TextField(default='', verbose_name='api说明')),
                ('demo', models.TextField(default='', verbose_name='api返回格式范例')),
                ('config', models.TextField(default='', verbose_name='配置json数据')),
            ],
            options={
                'verbose_name': 'Api接口模型',
                'verbose_name_plural': 'Api接口模型',
            },
        ),
        migrations.CreateModel(
            name='DisplayField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字段名')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.Api', verbose_name='api')),
            ],
            options={
                'verbose_name': 'API的查询字段',
                'verbose_name_plural': 'API的查询字段',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '容器'), (1, '单一条件')], verbose_name='条件类型')),
                ('field', models.CharField(max_length=50, null=True, verbose_name='条件字段名')),
                ('operator', models.CharField(max_length=20, verbose_name='条件判断符')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='条件值')),
                ('layer', models.IntegerField(default=0, verbose_name='嵌套层数')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.Api', verbose_name='api')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_db.Filter', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'API的查询条件',
                'verbose_name_plural': 'API的查询条件',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='参数名')),
                ('desc', models.CharField(max_length=100, verbose_name='备注')),
                ('type', models.CharField(choices=[('string', '字符串'), ('int', '整数'), ('decimal', '浮点数'), ('boolean', '布尔值'), ('json', 'json格式'), ('object', '复杂类型'), ('PAGE_SIZE', '页长'), ('PAGE_IDX', '页码'), ('pk', '主键')], max_length=20, verbose_name='参数类型')),
                ('required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('default', models.CharField(default='', max_length=50, null=True, verbose_name='默认值')),
                ('is_array', models.BooleanField(default=False, verbose_name='是否数组')),
                ('layer', models.IntegerField(default=0, verbose_name='嵌套层数')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.Api', verbose_name='api')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_db.Parameter', verbose_name='parent')),
            ],
            options={
                'verbose_name': '参数',
                'verbose_name_plural': '参数',
            },
        ),
        migrations.CreateModel(
            name='SetField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字段名')),
                ('value', models.CharField(max_length=200, verbose_name='赋值')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.Api', verbose_name='api')),
            ],
            options={
                'verbose_name': 'API的赋值字段',
                'verbose_name_plural': 'API的赋值字段',
                'ordering': ['name'],
            },
        ),
    ]
