# Generated by Django 2.1.3 on 2019-12-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setfield',
            name='layer',
            field=models.IntegerField(default=0, verbose_name='嵌套层数'),
        ),
        migrations.AddField(
            model_name='setfield',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_db.SetField', verbose_name='parent'),
        ),
    ]
