# Generated by Django 2.1.3 on 2019-12-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0002_auto_20191209_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='default',
            field=models.CharField(max_length=50, null=True, verbose_name='默认值'),
        ),
    ]
