# Generated by Django 2.1.3 on 2019-12-11 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('api_db', '0004_api_logined'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='permission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api', to='auth.Permission', verbose_name='权限'),
        ),
    ]
