# Generated by Django 2.1.3 on 2019-12-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0005_api_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='disable',
            field=models.BooleanField(default=False, verbose_name='停用'),
        ),
    ]
