# Generated by Django 2.1.3 on 2019-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0006_api_disable'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='名称'),
        ),
    ]
