# Generated by Django 2.1.3 on 2019-12-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('api_db', '0007_api_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='角色'),
        ),
    ]
