# Generated by Django 2.1.3 on 2019-12-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0008_api_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='use_default',
            field=models.BooleanField(default=True, verbose_name='是否使用默认值'),
        ),
    ]
