# Generated by Django 2.2 on 2020-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0009_parameter_use_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='operation',
            field=models.CharField(choices=[('list', '列表'), ('retrieve', '详情'), ('create', '新建'), ('update', '全部更新'), ('replace', '部分更新'), ('delete', '删除'), ('update_by_condition', '批量更新'), ('delete_by_condition', '批量删除'), ('func', '云函数')], max_length=20, verbose_name='操作'),
        ),
    ]
