# Generated by Django 2.1.3 on 2019-12-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0009_parameter_use_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='标识')),
                ('app', models.CharField(max_length=50, verbose_name='app名字')),
                ('model', models.CharField(max_length=50, verbose_name='数据模型名字')),
                ('name', models.CharField(default='', max_length=50, verbose_name='名称')),
                ('summary', models.TextField(default='', verbose_name='api说明')),
                ('event', models.CharField(choices=[('before_create', '创建前'), ('after_create', '创建后'), ('before_update', '更新前'), ('after_update', '更新后'), ('before_delete', '删除前'), ('after_delete', '删除后')], max_length=20, verbose_name='操作')),
            ],
            options={
                'verbose_name': '触发器',
                'verbose_name_plural': '触发器',
            },
        ),
        migrations.CreateModel(
            name='TriggerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reject', '拒绝存储'), ('create', '创建记录'), ('update', '更新记录'), ('delete', '删除记录')], max_length=20, verbose_name='条件类型')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.Trigger', verbose_name='trigger')),
            ],
            options={
                'verbose_name': '触发器行为',
                'verbose_name_plural': '触发器行为',
            },
        ),
        migrations.CreateModel(
            name='TriggerActionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '容器'), (1, '单一条件')], verbose_name='条件类型')),
                ('field', models.CharField(max_length=50, null=True, verbose_name='条件字段名')),
                ('operator', models.CharField(max_length=20, null=True, verbose_name='条件判断符')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='条件值')),
                ('layer', models.IntegerField(default=0, verbose_name='嵌套层数')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.TriggerAction', verbose_name='trigger')),
            ],
            options={
                'verbose_name': '触发器写行为',
                'verbose_name_plural': '触发器写行为',
            },
        ),
        migrations.CreateModel(
            name='TriggerActionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default='', max_length=200, verbose_name='字段名')),
                ('value', models.TextField(default='', verbose_name='赋值')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.TriggerAction', verbose_name='trigger')),
            ],
            options={
                'verbose_name': '触发器写行为',
                'verbose_name_plural': '触发器写行为',
            },
        ),
        migrations.CreateModel(
            name='TriggerFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '容器'), (1, '单一条件')], verbose_name='条件类型')),
                ('field', models.CharField(max_length=50, null=True, verbose_name='条件字段名')),
                ('operator', models.CharField(max_length=20, null=True, verbose_name='条件判断符')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='条件值')),
                ('layer', models.IntegerField(default=0, verbose_name='嵌套层数')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_db.TriggerFilter', verbose_name='parent')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.Trigger', verbose_name='trigger')),
            ],
            options={
                'verbose_name': '触发器条件',
                'verbose_name_plural': '触发器条件',
            },
        ),
    ]
