# Generated by Django 2.2 on 2020-01-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0014_trigger_disable'),
        ('api_db', '0010_auto_20200109_0024'),
    ]

    operations = [
    ]
