# Generated by Django 2.1.3 on 2020-01-13 08:40

import api_basebone.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0014_trigger_disable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggeractionfilter',
            name='action',
        ),
        migrations.RemoveField(
            model_name='triggeractionfilter',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='triggeractionset',
            name='action',
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='app',
            field=models.CharField(default='', max_length=50, verbose_name='app名字'),
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='fields',
            field=api_basebone.core.fields.JSONField(blank=True, default={}, verbose_name='操作的属性'),
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='filters',
            field=api_basebone.core.fields.JSONField(blank=True, default=[], verbose_name='操作的条件'),
        ),
        migrations.AddField(
            model_name='triggeraction',
            name='model',
            field=models.CharField(default='', max_length=50, verbose_name='数据模型名字'),
        ),
        migrations.AlterField(
            model_name='triggeraction',
            name='action',
            field=models.CharField(choices=[('reject', '终止执行'), ('modify', '修改参数'), ('create', '创建记录'), ('update', '更新记录'), ('delete', '删除记录')], max_length=20, verbose_name='条件类型'),
        ),
        migrations.DeleteModel(
            name='TriggerActionFilter',
        ),
        migrations.DeleteModel(
            name='TriggerActionSet',
        ),
    ]
