# Generated by Django 2.1.3 on 2020-01-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0016_auto_20200113_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triggerfilter',
            old_name='value',
            new_name='expression',
        ),
    ]
