# Generated by Django 2.1.3 on 2020-01-14 08:12

import api_basebone.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0017_auto_20200113_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50, null=True, verbose_name='app名字')),
                ('model', models.CharField(max_length=50, null=True, verbose_name='数据模型名字')),
                ('filters', api_basebone.core.fields.JSONField(blank=True, default=[], verbose_name='筛选条件')),
            ],
            options={
                'verbose_name': '触发器条件',
                'verbose_name_plural': '触发器条件',
            },
        ),
        migrations.RemoveField(
            model_name='triggerfilter',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='triggerfilter',
            name='trigger',
        ),
        migrations.AlterIndexTogether(
            name='trigger',
            index_together=set(),
        ),
        migrations.DeleteModel(
            name='TriggerFilter',
        ),
        migrations.AddField(
            model_name='triggercondition',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_db.Trigger', verbose_name='trigger'),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='app',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='model',
        ),
        migrations.AlterIndexTogether(
            name='triggercondition',
            index_together={('app', 'model')},
        ),
    ]
