# Generated by Django 2.2 on 2020-01-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0019_auto_20200114_1615'),
        ('api_db', '0015_merge_20200116_1909'),
    ]

    operations = [
    ]
