# Generated by Django 2.2 on 2020-01-17 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0020_merge_20200116_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggercondition',
            name='trigger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_db.Trigger', verbose_name='trigger_condition'),
        ),
    ]
