# Generated by Django 2.1.3 on 2020-01-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0021_auto_20200117_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggeraction',
            name='trigger',
        ),
        migrations.AlterIndexTogether(
            name='triggercondition',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='triggercondition',
            name='trigger',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
        migrations.DeleteModel(
            name='TriggerAction',
        ),
        migrations.DeleteModel(
            name='TriggerCondition',
        ),
    ]
