# Generated by Django 2.2.17 on 2021-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0023_function_functionparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='描述'),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('model', 'name')},
        ),
        migrations.RemoveField(
            model_name='function',
            name='app',
        ),
    ]
