# Generated by Django 2.2.17 on 2021-02-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0025_auto_20210203_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='scene',
            field=models.CharField(choices=[('unlimit', '不限制'), ('inline', '单行操作'), ('batch', '批量操作')], default='unlimit', max_length=20, verbose_name='应用场景'),
        ),
        migrations.AlterField(
            model_name='function',
            name='type',
            field=models.IntegerField(choices=[(0, '行操作'), (1, '全局操作'), (2, '批量操作'), (3, '其他')], default=0, verbose_name='类型'),
        ),
    ]
