# Generated by Django 2.2.17 on 2021-02-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0026_auto_20210205_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='type',
        ),
    ]
