# Generated by Django 2.2.17 on 2021-03-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_db', '0030_auto_20210301_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionparameter',
            name='type',
            field=models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('decimal', '浮点数'), ('bool', '布尔值'), ('date', '日期'), ('ref', '数据'), ('image', '图片')], max_length=20, verbose_name='类型'),
        ),
    ]
